
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author ylhaart
 */
public class GraphicsProgram extends javax.swing.JFrame {

    /**
     * Creates new form GraphicsProgram
     */
    public GraphicsProgram() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popup = new javax.swing.JPopupMenu();
        setImageItem = new javax.swing.JMenuItem();
        setUpperItem = new javax.swing.JMenuItem();
        setLowerItem = new javax.swing.JMenuItem();
        pictureGraphics1 = new PictureGraphics();

        setImageItem.setText("Set image...");
        setImageItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setImageItemActionPerformed(evt);
            }
        });
        popup.add(setImageItem);

        setUpperItem.setText("Set upper...");
        setUpperItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setUpperItemActionPerformed(evt);
            }
        });
        popup.add(setUpperItem);

        setLowerItem.setText("Set lower...");
        setLowerItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setLowerItemActionPerformed(evt);
            }
        });
        popup.add(setLowerItem);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Exercise 5.2");

        pictureGraphics1.setComponentPopupMenu(popup);

        javax.swing.GroupLayout pictureGraphics1Layout = new javax.swing.GroupLayout(pictureGraphics1);
        pictureGraphics1.setLayout(pictureGraphics1Layout);
        pictureGraphics1Layout.setHorizontalGroup(
            pictureGraphics1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        pictureGraphics1Layout.setVerticalGroup(
            pictureGraphics1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pictureGraphics1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pictureGraphics1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setUpperItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setUpperItemActionPerformed
        System.out.println("Set upper item chosen");
    }//GEN-LAST:event_setUpperItemActionPerformed

    private void setLowerItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setLowerItemActionPerformed
        System.out.println("Set lower item chosen");
    }//GEN-LAST:event_setLowerItemActionPerformed

    private void setImageItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setImageItemActionPerformed
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "Images", "jpg", "gif", "png");
        chooser.setFileFilter(filter);
        chooser.setDialogTitle("Choose a picture file");
        int r = chooser.showDialog(getContentPane(), "Open");
        if (r == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            try {
                pictureGraphics1.setImage(ImageIO.read(file));
            } catch (IOException ex) {
                Logger.getLogger(GraphicsProgram.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_setImageItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraphicsProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraphicsProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraphicsProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraphicsProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraphicsProgram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private PictureGraphics pictureGraphics1;
    private javax.swing.JPopupMenu popup;
    private javax.swing.JMenuItem setImageItem;
    private javax.swing.JMenuItem setLowerItem;
    private javax.swing.JMenuItem setUpperItem;
    // End of variables declaration//GEN-END:variables
}
